<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AtmSeeder extends Seeder
{
    public function run(): void


    {
        $now = Carbon::now();
        $atms = [

            ///////////////////////////////////////////// Jimma District ATMs ////////////////////////////////////////////////////////////////
            ['id' => 1, 'terminal' => 'PATML059', 'name' => 'ABAJIFAR ATM', 'os' => '7', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 30, 'ipAddress' => '172.21.16.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'terminal' => 'PATML133', 'name' => 'FERENJ ARADA ATM', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 31, 'ipAddress' => '172.20.149.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:08:14'],
            ['id' => 3, 'terminal' => 'PATML167', 'name' => 'LIMU GENT ATM', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 3, 'ipAddress' => '192.168.96.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:08:44'],
            ['id' => 4, 'terminal' => 'PATML185', 'name' => 'AGARO ATM', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 2, 'ipAddress' => '172.19.15.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:09:10'],
            ['id' => 5, 'terminal' => 'PATML228', 'name' => 'JIMMA 2 ATM', 'os' => 'Windows 10 Build 14393 Intel IA-32', 'type' => 'ATM', 'location' => 'JIMMA', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.154', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'terminal' => 'PATMT077', 'name' => 'Yayo', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 11, 'ipAddress' => '172.23.179.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:09:49'],
            ['id' => 7, 'terminal' => 'PATMT151', 'name' => 'METU ATM', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 12, 'ipAddress' => '192.168.90.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:10:12'],
            ['id' => 8, 'terminal' => 'PATMT074', 'name' => 'Jimma Ferenj Arada_2 Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 31, 'ipAddress' => '172.20.149.153', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:10:40'],
            ['id' => 9, 'terminal' => 'PATMT069', 'name' => 'Silk Amba Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 23, 'ipAddress' => '172.23.221.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:11:13'],
            ['id' => 10, 'terminal' => 'PATML177', 'name' => 'Jimma Branch', 'os' => '', 'type' => 'ATM', 'location' => 'Jimma', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.153', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'terminal' => 'PAGRL191', 'name' => 'Masha Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 14, 'ipAddress' => '172.21.77.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:11:50'],
            ['id' => 12, 'terminal' => 'PAGRL194', 'name' => 'Denebe(sokoru) Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 19, 'ipAddress' => '172.21.235.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:12:18'],
            ['id' => 13, 'terminal' => 'PAGRL196', 'name' => 'Meti Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 15, 'ipAddress' => '172.21.182.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:12:40'],
            ['id' => 14, 'terminal' => 'PAGRL197', 'name' => 'Jimma Main Branch', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'ATM', 'location' => 'JIMMA', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.155', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'terminal' => 'PAGRL253', 'name' => 'Alif Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 24, 'ipAddress' => '172.19.30.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:13:09'],
            ['id' => 16, 'terminal' => 'PAGRL257', 'name' => 'Gechi Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 13, 'ipAddress' => '172.21.69.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:13:37'],
            ['id' => 17, 'terminal' => 'PAGRL254', 'name' => 'Abajifar Main', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 29, 'ipAddress' => '172.21.165.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:14:07'],
            ['id' => 18, 'terminal' => 'PAGRL400', 'name' => 'Hermata Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 26, 'ipAddress' => '172.21.73.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:14:27'],
            ['id' => 19, 'terminal' => 'PAGRL401', 'name' => 'Iqra Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 28, 'ipAddress' => '172.21.74.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:15:00'],
            ['id' => 20, 'terminal' => 'PAGRL402', 'name' => 'Bedele branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 8, 'ipAddress' => '192.168.154.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:15:24'],
            ['id' => 21, 'terminal' => 'PAGRL403', 'name' => 'Jimma Menahira Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 27, 'ipAddress' => '172.20.94.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:15:57'],
            ['id' => 22, 'terminal' => 'PAGRL404', 'name' => 'Saja Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 20, 'ipAddress' => '172.21.115.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:16:18'],
            ['id' => 23, 'terminal' => 'PAGRL463', 'name' => 'Tolay Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 22, 'ipAddress' => '172.23.142.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:17:15'],
            ['id' => 24, 'terminal' => 'PAGRL631', 'name' => 'Jimma Haile Resort', 'os' => '10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 27, 'ipAddress' => '172.22.141.60', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:17:35'],
            ['id' => 25, 'terminal' => 'PAGRL637', 'name' => 'Gumerro Tea', 'os' => '10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 12, 'ipAddress' => '172.29.90.8', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:18:16'],
            ['id' => 26, 'terminal' => 'PAGRL774', 'name' => 'Jimma ATM center 2', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'ATM', 'location' => 'JIMMA', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.157', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'terminal' => 'PAGRL773', 'name' => 'Jimma ATM center 1', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'ATM', 'location' => 'JIMMA', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.156', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'terminal' => 'PAGRL717', 'name' => 'Mettu Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 12, 'ipAddress' => '192.168.90.153', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:01:46'],
            ['id' => 29, 'terminal' => 'PAGRL764', 'name' => 'Chida Branch', 'os' => '10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 18, 'ipAddress' => '172.21.236.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:01:22'],
            ['id' => 30, 'terminal' => 'PAGRR823', 'name' => 'Jimma Merkato Market', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 2TB HDD', 'type' => 'Recycler', 'location' => 'Jimma', 'design' => 'Lobby', 'branch_id' => 1, 'ipAddress' => '192.168.163.159', 'networkType' => 'Broadband', 'remark' => '', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'terminal' => 'PATML166', 'name' => 'Limmu Genet_2 Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 3, 'ipAddress' => '192.168.96.153', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:00:53'],
            ['id' => 32, 'terminal' => 'PATML176', 'name' => 'Gecha Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 7, 'ipAddress' => '172.21.78.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 05:00:29'],
            ['id' => 33, 'terminal' => 'PATML180', 'name' => 'Agaro_2 Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 2, 'ipAddress' => '172.19.15.153', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 04:58:11'],
            ['id' => 34, 'terminal' => 'PATML184', 'name' => 'IFB Al-nur Agaro Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 6, 'ipAddress' => '172.20.87.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 04:57:40'],
            ['id' => 35, 'terminal' => 'PATML186', 'name' => 'Shebe Branch', 'os' => '10', 'type' => 'NCR', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 17, 'ipAddress' => '172.23.60.53', 'networkType' => 'Broadband', 'remark' => NULL, 'created_at' => now(), 'updated_at' => '2026-01-09 04:57:12'],



            ///////////////////////////////////////////////// South West District ATMs //////////////////////////////////////////////////////////////
            ['id' => 36, 'terminal' => 'PATML132', 'name' => 'Shishonde', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.20.123.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'terminal' => 'PATMT081', 'name' => 'Bonga', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '192.168.206.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'terminal' => 'PATMT085', 'name' => 'Mizan', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '192.168.191.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'terminal' => 'PATML266', 'name' => 'Tarekegn Tadesse Com.center', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.22.149.234', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'terminal' => 'PATMT080', 'name' => 'Bonga Branch #3', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '192.168.206.156', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'terminal' => 'PAGRL190', 'name' => 'Gessa Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.21.68.2', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'terminal' => 'PAGRL457', 'name' => 'Gesha Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.20.170.1', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'terminal' => 'PAGRL462', 'name' => 'Al-Baaraka Teppi Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.23.253.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'terminal' => 'PAGRL455', 'name' => 'Berges Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.23.Windows 106.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'terminal' => 'PAGRL461', 'name' => 'Shay Bench', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.20.169.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'terminal' => 'PAGRL459', 'name' => 'Makira Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.23.83.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'terminal' => 'PAGRL456', 'name' => 'Bonga Branch', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '192.168.206.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'terminal' => 'PAGRL458', 'name' => 'Gojeb', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.23.184.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'terminal' => 'PAGRL636', 'name' => 'Bonga university', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.22.144.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'terminal' => 'PAGRL635', 'name' => 'Mintesint Tesfaye Building', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '172.22.141.83', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'terminal' => 'PAGRL763', 'name' => 'Teppi Branch2', 'os' => 'Windows Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => '192.168.58.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'terminal' => 'PAGRL199', 'name' => 'Aman Branch', 'ipAddress' => '172.21.117.53', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'terminal' => 'PAGRL195', 'name' => 'Dima Branch', 'ipAddress' => '172.21.181.53', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'terminal' => 'PAGRL460', 'name' => 'Mizan2', 'ipAddress' => '192.168.191.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'terminal' => 'PAGRL632', 'name' => 'Dimma Branch 2', 'ipAddress' => '172.21.181.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'terminal' => 'PAGRL630', 'name' => 'Tercha branch', 'ipAddress' => '172.20.168.53', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'terminal' => 'PAGRL762', 'name' => 'Saylem Branch', 'ipAddress' => '172.23.128.53', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'terminal' => 'PAGRL252', 'name' => 'Wonber Yosef Market Center', 'ipAddress' => '172.22.147.212', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'terminal' => 'PATML229', 'name' => 'Bita Branch', 'ipAddress' => '172.21.151.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'terminal' => 'PATML234', 'name' => 'Goba Dishi Branch', 'ipAddress' => '172.23.186.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'terminal' => 'PATML243', 'name' => 'Bachuma Branch', 'ipAddress' => '172.21.116.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'terminal' => 'PATML264', 'name' => 'Jemu branch', 'ipAddress' => '172.21.157.153', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'On-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'terminal' => 'PATML265', 'name' => 'Meseret Welde Commercial center', 'ipAddress' => '172.22.149.226', 'os' => 'Windows 10', 'type' => 'GRG', 'location' => 'Off-branch', 'design' => 'Lobby', 'branch_id' => 36, 'ipAddress' => null, 'networkType' => 'Broadband', 'remark' => null, 'created_at' => now(), 'updated_at' => now()],


            ///////////////////////////// Nekemte District ATMs //////////////////////////////////////////////////////////////////////////
            ['id' => 64, 'terminal' => 'PATML227', 'name' => 'Baro Mado', 'os' => 'windows 7 Professional 32-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.20.171.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 65, 'terminal' => 'PATMT078', 'name' => 'Gambella', 'os' => 'windows 7 Professional 32-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.169.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 66, 'terminal' => 'PATMT079', 'name' => 'Nekemte', 'os' => 'windows 7 Professional 32-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.144.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 67, 'terminal' => 'PATMT171', 'name' => 'Dembi dolo', 'os' => 'Windows 10 Enterprise 2016 LTSB 64-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.20.122.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 68, 'terminal' => 'PATML183', 'name' => 'Gimbi', 'os' => 'Windows 10 Enterprise 2016 LTSB 64-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.20.121.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 69, 'terminal' => 'PATMT042', 'name' => 'Ambo', 'os' => 'windows 7 Professional 32-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.166.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 70, 'terminal' => 'PAGRL192', 'name' => 'Terfam Branch', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.183.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 71, 'terminal' => 'PAGRL255', 'name' => 'Meklit Hotel', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.22.141.66/24', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 72, 'terminal' => 'PAGRL399', 'name' => 'Gambella new Land', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.7.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 73, 'terminal' => 'PAGRL454', 'name' => 'Benishangul Branch', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.237.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 74, 'terminal' => 'PAGRL464', 'name' => 'Gambella Hospital', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.22.144.141/24', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 75, 'terminal' => 'PAGRL628', 'name' => 'Bambasi', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.238.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 76, 'terminal' => 'PAGRL629', 'name' => 'Nekemte Branch2', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.144.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 77, 'terminal' => 'PAGRL633', 'name' => 'Arumela', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.22.144.132/29', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 78, 'terminal' => 'PAGRL678', 'name' => 'Baro Mado Branch', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.20.171.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 79, 'terminal' => 'PAGRL752', 'name' => 'Gambella New land2', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.7.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 80, 'terminal' => 'PAGRL472', 'name' => 'Yai Geda', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.40.53', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 81, 'terminal' => 'PAGRL198', 'name' => 'Gambela General Hospital', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.22.148.210/29', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 82, 'terminal' => 'PAGRL799', 'name' => 'Assosa Branch', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 21H2', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.54.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 83, 'terminal' => 'PAGRR811', 'name' => 'Gambella', 'os' => 'Microsoft Windows 10 IoT Enterprise LTSC 64-bit 2TB HDD', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '192.168.169.158', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 84, 'terminal' => 'PATML158', 'name' => 'Yai Geda Branch', 'os' => 'Win 10 IOT Enterprise LTSC 64-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.40.155', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 85, 'terminal' => 'PATML160', 'name' => 'Shambu Branch', 'os' => 'Win 10 IOT Enterprise LTSC 64-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.19.19.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 86, 'terminal' => 'PATML164', 'name' => 'wollga University/Bake Jama #2', 'os' => 'Win 10 IOT Enterprise LTSC 64-bit', 'type' => 'GRG', 'location' => 'On-branch', 'design' => null, 'branch_id' => 34, 'ipAddress' => '172.21.75.153', 'networkType' => 'Broadband', 'remark' => null, 'created_at' => $now, 'updated_at' => $now],



        ];

        DB::table('a_t_m_s')->insert($atms);
    }
}
